interface Records {
  id: number;
  assignedHours: number;
  name: string;
  timeSheet: string;
  company: string;
  projects: string;
}

interface ExpandableRecords {
  id: number;
  assignedHours: number;
  name: string;
  timeSheet: string;
  company: string;
  projects: string;
  subRows: Records[];
}

const records: Records[] = [
  {
    id: 1,
    assignedHours: 32,
    name: "Burt",
    timeSheet: "28 April 2024",
    company: "Kaggle",
    projects: "Office Management",
  },
  {
    id: 2,
    assignedHours: 23,
    name: "Bruno",
    timeSheet: "29 April 2024",

    company: "Magmina",
    projects: "Web App",
  },
  {
    id: 3,
    assignedHours: 31,
    name: "Alvarado",
    timeSheet: "25 April 2024",
    
    company: "Translink",
    projects: "Video Calling",
  },
  {
    id: 4,
    assignedHours: 24,
    name: "Lilia",
    timeSheet: "20 April 2024",

    company: "Digitalus",
    projects: "Hospital Management",
  },
  {
    id: 5,
    assignedHours: 25,
    name: "Amanda",
    timeSheet: "15 April 2024",
    company: "Bunga",
    projects: "School Management",
  },
  {
    id: 6,
    assignedHours: 20,
    name: "Alexandra",
    timeSheet: "15 April 2024",
    company: "Conjurica",
    projects: "Office Management",
  },
  {
    id: 7,
    assignedHours: 27,
    name: "Diana",
    timeSheet: "15 April 2024",
    company: "Extragen",
    projects: "Office Management",
  },
  {
    id: 8,
    assignedHours: 26,
    name: "Goodman",
    timeSheet: "15 April 2024",
    company: "Aquamate",
    projects: "Office Management",
  },
  {
    id: 9,
    assignedHours: 26,
    name: "Edith",
    timeSheet: "15 April 2024",
    company: "Pyrami",
    projects: "Office Management",
  },
  {
    id: 10,
    assignedHours: 29,
    name: "Juana",
    timeSheet: "15 April 2024",
    company: "Singavera",
    projects: "Office Management",
  },
  {
    id: 11,
    assignedHours: 21,
    name: "Fitzgerald",
    timeSheet: "15 April 2024",
    company: "Dancerity",
    projects: "Office Management",
  },
  {
    id: 12,
    assignedHours: 38,
    name: "Madden",
    timeSheet: "15 April 2024",
    company: "Corpulse",
    projects: "Office Management",
  },
  {
    id: 13,
    assignedHours: 40,
    name: "Jewell",
    timeSheet: "15 April 2024",
    company: "Frenex",
    projects: "Office Management",
  },
  {
    id: 14,
    assignedHours: 32,
    name: "Kerr",
    timeSheet: "15 April 2024",
    company: "Artiq",
    projects: "Office Management",
  },
  {
    id: 15,
    assignedHours: 20,
    name: "Washington",
    timeSheet: "15 April 2024",
    company: "Organica",
    projects: "Office Management",
  },
  {
    id: 16,
    assignedHours: 20,
    name: "Audrey",
    timeSheet: "15 April 2024",
    company: "Softmicro",
    projects: "Office Management",
  },
  {
    id: 17,
    assignedHours: 39,
    name: "Allison",
    timeSheet: "15 April 2024",
    company: "Playce",
    projects: "Office Management",
  },
  {
    id: 18,
    assignedHours: 25,
    name: "Holder",
    timeSheet: "15 April 2024",
    company: "Paragonia",
    projects: "Office Management",
  },
  {
    id: 19,
    assignedHours: 26,
    name: "Atkinson",
    timeSheet: "15 April 2024",
    company: "Scentric",
    projects: "Office Management",
  },
  {
    id: 20,
    assignedHours: 35,
    name: "Delaney",
    timeSheet: "15 April 2024",
    company: "Telpod",
    projects: "Office Management",
  },
  {
    id: 21,
    assignedHours: 20,
    name: "Myrna",
    timeSheet: "15 April 2024",
    company: "Zanity",
    projects: "Office Management",
  },
  {
    id: 22,
    assignedHours: 30,
    name: "Erna",
    timeSheet: "15 April 2024",
    company: "Techade",
    projects: "Office Management",
  },
  {
    id: 23,
    assignedHours: 36,
    name: "Fannie",
    timeSheet: "15 April 2024",
    company: "Cubix",
    projects: "Office Management",
  },
  {
    id: 24,
    assignedHours: 38,
    name: "Melody",
    timeSheet: "15 April 2024",
    company: "Talae",
    projects: "Office Management",
  },
  {
    id: 25,
    assignedHours: 27,
    name: "Letitia",
    timeSheet: "15 April 2024",
    company: "Enjola",
    projects: "Office Management",
  },
  {
    id: 26,
    assignedHours: 33,
    name: "Nina",
    timeSheet: "15 April 2024",
    company: "Eventex",
    projects: "Office Management",
  },
  {
    id: 27,
    assignedHours: 40,
    name: "Byrd",
    timeSheet: "15 April 2024",
    company: "Obones",
    projects: "Office Management",
  },
  {
    id: 28,
    assignedHours: 34,
    name: "Chen",
    timeSheet: "15 April 2024",
    company: "Dadabase",
    projects: "Office Management",
  },
  {
    id: 29,
    assignedHours: 25,
    name: "Alexandria",
    timeSheet: "15 April 2024",
    company: "Turnabout",
    projects: "Office Management",
  },
  {
    id: 30,
    assignedHours: 37,
    name: "Page",
    timeSheet: "15 April 2024",
    company: "Metroz",
    projects: "Office Management",
  },
  {
    id: 31,
    assignedHours: 24,
    name: "Clare",
    timeSheet: "15 April 2024",
    company: "Zilch",
    projects: "Office Management",
  },
  {
    id: 32,
    assignedHours: 38,
    name: "Lindsey",
    timeSheet: "15 April 2024",
    company: "Roughies",
    projects: "Office Management",
  },
  {
    id: 33,
    assignedHours: 32,
    name: "Oconnor",
    timeSheet: "15 April 2024",
    company: "Kinetica",
    projects: "Office Management",
  },
  {
    id: 34,
    assignedHours: 35,
    name: "Maldonado",
    timeSheet: "15 April 2024",
    company: "Zentime",
    projects: "Office Management",
  },
  {
    id: 35,
    assignedHours: 25,
    name: "Day",
    timeSheet: "15 April 2024",
    company: "Eargo",
    projects: "Office Management",
  },
  {
    id: 36,
    assignedHours: 20,
    name: "Collier",
    timeSheet: "15 April 2024",
    company: "Phuel",
    projects: "Office Management",
  },
  {
    id: 37,
    assignedHours: 40,
    name: "Jeannette",
    timeSheet: "15 April 2024",
    company: "Entogrok",
    projects: "Office Management",
  },
  {
    id: 38,
    assignedHours: 33,
    name: "Wallace",
    timeSheet: "15 April 2024",
    company: "Nurali",
    projects: "Office Management",
  },
  {
    id: 39,
    assignedHours: 39,
    name: "Mcfadden",
    timeSheet: "15 April 2024",
    company: "Cincyr",
    projects: "Office Management",
  },
  {
    id: 40,
    assignedHours: 21,
    name: "Chrystal",
    timeSheet: "15 April 2024",
    company: "Futurize",
    projects: "Office Management",
  },
  {
    id: 41,
    assignedHours: 31,
    name: "Leila",
    timeSheet: "15 April 2024",
    company: "Zensure",
    projects: "Office Management",
  },
  {
    id: 42,
    assignedHours: 24,
    name: "Madelyn",
    timeSheet: "15 April 2024",
    company: "Egypto",
    projects: "Office Management",
  },
  {
    id: 43,
    assignedHours: 39,
    name: "Peck",
    timeSheet: "15 April 2024",
    company: "Tellifly",
    projects: "Office Management",
  },
  {
    id: 44,
    assignedHours: 32,
    name: "Garrett",
    timeSheet: "15 April 2024",
    company: "Aquasure",
    projects: "Office Management",
  },
  {
    id: 45,
    assignedHours: 21,
    name: "Kramer",
    timeSheet: "15 April 2024",
    company: "Terrago",
    projects: "Office Management",
  },
  {
    id: 46,
    assignedHours: 35,
    name: "Lane",
    timeSheet: "15 April 2024",
    company: "Anivet",
    projects: "Office Management",
  },
  {
    id: 47,
    assignedHours: 21,
    name: "Merritt",
    timeSheet: "15 April 2024",
    company: "Inear",
    projects: "Office Management",
  },
  {
    id: 48,
    assignedHours: 25,
    name: "Margarita",
    timeSheet: "15 April 2024",
    company: "Unq",
    projects: "Office Management",
  },
  {
    id: 49,
    assignedHours: 28,
    name: "Leigh",
    timeSheet: "15 April 2024",
    company: "Marqet",
    projects: "Office Management",
  },
  {
    id: 50,
    assignedHours: 31,
    name: "Coleman",
    timeSheet: "15 April 2024",
    company: "Insuresys",
    projects: "Office Management",
  },
  {
    id: 51,
    assignedHours: 31,
    name: "Alexander",
    timeSheet: "15 April 2024",
    company: "Portico",
    projects: "Office Management",
  },
  {
    id: 52,
    assignedHours: 38,
    name: "Tanisha",
    timeSheet: "15 April 2024",
    company: "Earthwax",
    projects: "Office Management",
  },
  {
    id: 53,
    assignedHours: 23,
    name: "Crane",
    timeSheet: "15 April 2024",
    company: "Pushcart",
    projects: "Office Management",
  },
  {
    id: 54,
    assignedHours: 26,
    name: "Carmella",
    timeSheet: "15 April 2024",
    company: "Acusage",
    projects: "Office Management",
  },
  {
    id: 55,
    assignedHours: 27,
    name: "Rosalind",
    timeSheet: "15 April 2024",
    company: "Isologica",
    projects: "Office Management",
  },
  {
    id: 56,
    assignedHours: 37,
    name: "Duran",
    timeSheet: "15 April 2024",
    company: "Gazak",
    projects: "Office Management",
  },
  {
    id: 57,
    assignedHours: 27,
    name: "Bernard",
    timeSheet: "15 April 2024",
    company: "Zoinage",
    projects: "Office Management",
  },
  {
    id: 58,
    assignedHours: 29,
    name: "Tate",
    timeSheet: "15 April 2024",
    company: "Endipine",
    projects: "Office Management",
  },
  {
    id: 59,
    assignedHours: 39,
    name: "Pearlie",
    timeSheet: "15 April 2024",
    company: "Progenex",
    projects: "Office Management",
  },
  {
    id: 60,
    assignedHours: 20,
    name: "Manning",
    timeSheet: "15 April 2024",
    company: "Handshake",
    projects: "Office Management",
  },
];

const expandableRecords: ExpandableRecords[] = [
  {
    id: 1,
    assignedHours: 32,
    name: "Burt",
    timeSheet: "15 April 2024",
    company: "Kaggle",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 2,
    assignedHours: 23,
    name: "Long",
    timeSheet: "15 April 2024",
    company: "Magmina",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 3,
    assignedHours: 31,
    name: "Alvarado",
    timeSheet: "15 April 2024",
    company: "Translink",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 4,
    assignedHours: 24,
    name: "Lilia",
    timeSheet: "15 April 2024",
    company: "Digitalus",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 5,
    assignedHours: 25,
    name: "Amanda",
    timeSheet: "15 April 2024",
    company: "Bunga",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 6,
    assignedHours: 20,
    name: "Alexandra",
    timeSheet: "15 April 2024",
    company: "Conjurica",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 7,
    assignedHours: 27,
    name: "Diana",
    timeSheet: "15 April 2024",
    company: "Extragen",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 8,
    assignedHours: 26,
    name: "Goodman",
    timeSheet: "15 April 2024",
    company: "Aquamate",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 9,
    assignedHours: 26,
    name: "Edith",
    timeSheet: "15 April 2024",
    company: "Pyrami",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 10,
    assignedHours: 29,
    name: "Juana",
    timeSheet: "15 April 2024",
    company: "Singavera",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 11,
    assignedHours: 21,
    name: "Fitzgerald",
    timeSheet: "15 April 2024",
    company: "Dancerity",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 12,
    assignedHours: 38,
    name: "Madden",
    timeSheet: "15 April 2024",
    company: "Corpulse",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 13,
    assignedHours: 40,
    name: "Jewell",
    timeSheet: "15 April 2024",
    company: "Frenex",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 14,
    assignedHours: 32,
    name: "Kerr",
    timeSheet: "15 April 2024",
    company: "Artiq",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 15,
    assignedHours: 20,
    name: "Washington",
    timeSheet: "15 April 2024",
    company: "Organica",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 16,
    assignedHours: 20,
    name: "Audrey",
    timeSheet: "15 April 2024",
    company: "Softmicro",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 17,
    assignedHours: 39,
    name: "Allison",
    timeSheet: "15 April 2024",
    company: "Playce",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 18,
    assignedHours: 25,
    name: "Holder",
    timeSheet: "15 April 2024",
    company: "Paragonia",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 19,
    assignedHours: 26,
    name: "Atkinson",
    timeSheet: "15 April 2024",
    company: "Scentric",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 20,
    assignedHours: 35,
    name: "Delaney",
    timeSheet: "15 April 2024",
    company: "Telpod",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 21,
    assignedHours: 20,
    name: "Myrna",
    timeSheet: "15 April 2024",
    company: "Zanity",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 22,
    assignedHours: 30,
    name: "Erna",
    timeSheet: "15 April 2024",
    company: "Techade",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 23,
    assignedHours: 36,
    name: "Fannie",
    timeSheet: "15 April 2024",
    company: "Cubix",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 24,
    assignedHours: 38,
    name: "Melody",
    timeSheet: "15 April 2024",
    company: "Talae",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 25,
    assignedHours: 27,
    name: "Letitia",
    timeSheet: "15 April 2024",
    company: "Enjola",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 26,
    assignedHours: 33,
    name: "Nina",
    timeSheet: "15 April 2024",
    company: "Eventex",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 27,
    assignedHours: 40,
    name: "Byrd",
    timeSheet: "15 April 2024",
    company: "Obones",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 28,
    assignedHours: 34,
    name: "Chen",
    timeSheet: "15 April 2024",
    company: "Dadabase",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 29,
    assignedHours: 25,
    name: "Alexandria",
    timeSheet: "15 April 2024",
    company: "Turnabout",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 30,
    assignedHours: 37,
    name: "Page",
    timeSheet: "15 April 2024",
    company: "Metroz",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 31,
    assignedHours: 24,
    name: "Clare",
    timeSheet: "15 April 2024",
    company: "Zilch",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 32,
    assignedHours: 38,
    name: "Lindsey",
    timeSheet: "15 April 2024",
    company: "Roughies",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 33,
    assignedHours: 32,
    name: "Oconnor",
    timeSheet: "15 April 2024",
    company: "Kinetica",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 34,
    assignedHours: 35,
    name: "Maldonado",
    timeSheet: "15 April 2024",
    company: "Zentime",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 35,
    assignedHours: 25,
    name: "Day",
    timeSheet: "15 April 2024",
    company: "Eargo",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 36,
    assignedHours: 20,
    name: "Collier",
    timeSheet: "15 April 2024",
    company: "Phuel",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 37,
    assignedHours: 40,
    name: "Jeannette",
    timeSheet: "15 April 2024",
    company: "Entogrok",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 38,
    assignedHours: 33,
    name: "Wallace",
    timeSheet: "15 April 2024",
    company: "Nurali",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 39,
    assignedHours: 39,
    name: "Mcfadden",
    timeSheet: "15 April 2024",
    company: "Cincyr",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
  {
    id: 40,
    assignedHours: 21,
    name: "Chrystal",
    timeSheet: "15 April 2024",
    company: "Futurize",
    projects: "Office Management",
    subRows: [
      {
        id: 51,
        assignedHours: 23,
        name: "Bruno",
        timeSheet: "15 April 2024",
        company: "Magmina",
        projects: "Office Management",
      },
    ],
  },
];
export { records, expandableRecords };
